/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ifcoder.projetodacc_jpa.view;

import javax.swing.JOptionPane;

/**
 *
 * @author jose
 */
public class FrMenuPrincipal extends javax.swing.JFrame {

    public FrMenuPrincipal() {
        initComponents();

//        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/remove_16x16.png"));
//        if (icon.getImageLoadStatus() != MediaTracker.COMPLETE) {
//            System.out.println("Erro ao carregar a imagem!");
//        } else {
//            System.out.println("Imagem carregada com sucesso!");
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenuPrincipal = new javax.swing.JLabel();
        btnCadAluno = new javax.swing.JButton();
        btnCadProfessor = new javax.swing.JButton();
        btnCadFuncionario = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        btnCadTurma = new javax.swing.JButton();
        btnCadDisciplina = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnSair = new javax.swing.JMenuItem();
        mnCadastros = new javax.swing.JMenu();
        mnCadAluno = new javax.swing.JMenuItem();
        mnCadProfessor = new javax.swing.JMenuItem();
        mnCadastrarFuncionarios = new javax.swing.JMenuItem();
        mnCadDisciplinas = new javax.swing.JMenuItem();
        mnCadTurmas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMenuPrincipal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblMenuPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuPrincipal.setText("DACC");

        btnCadAluno.setText("Alunos");
        btnCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadAlunoActionPerformed(evt);
            }
        });

        btnCadProfessor.setText("Professores");
        btnCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadProfessorActionPerformed(evt);
            }
        });

        btnCadFuncionario.setText("Funcionarios");
        btnCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadFuncionarioActionPerformed(evt);
            }
        });

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/DACC - logo2.png"))); // NOI18N
        lblLogo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnCadTurma.setText("Turmas");
        btnCadTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadTurmaActionPerformed(evt);
            }
        });

        btnCadDisciplina.setText("Disciplinas");
        btnCadDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadDisciplinaActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnSair);

        jMenuBar1.add(jMenu1);

        mnCadastros.setText("Cadastros");

        mnCadAluno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnCadAluno.setText("Cadastrar alunos");
        mnCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadAlunoActionPerformed(evt);
            }
        });
        mnCadastros.add(mnCadAluno);

        mnCadProfessor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnCadProfessor.setText("Cadastrar professores");
        mnCadProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadProfessorActionPerformed(evt);
            }
        });
        mnCadastros.add(mnCadProfessor);

        mnCadastrarFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnCadastrarFuncionarios.setText("Cadastrar Funcionários");
        mnCadastrarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarFuncionariosActionPerformed(evt);
            }
        });
        mnCadastros.add(mnCadastrarFuncionarios);

        mnCadDisciplinas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnCadDisciplinas.setText("Cadastrar Disciplinas");
        mnCadDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadDisciplinasActionPerformed(evt);
            }
        });
        mnCadastros.add(mnCadDisciplinas);

        mnCadTurmas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnCadTurmas.setText("Cadastrar Turmas");
        mnCadTurmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadTurmasActionPerformed(evt);
            }
        });
        mnCadastros.add(mnCadTurmas);

        jMenuBar1.add(mnCadastros);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadTurma, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                    .addComponent(lblMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProfessorActionPerformed
        FrProfessor dlgCadProfessor = new FrProfessor(this, true);

        // Configura o posicionamento relativo, faz o dialgo aparecer na mesma tela que o pai(qdo estamos mais de uma tela)
        dlgCadProfessor.setLocationRelativeTo(this);
        dlgCadProfessor.setVisible(true);

        /* Usando JFrame.
        Esta forma não é legal, dado que temos mais de uma aplicacao na barra de tarefas. 
        Dê preferencia por fazer a dinamica de telas usando JDialog como acima.
       
        FrProfessor telaProfessor = new FrProfessor(this);
        telaProfessor.setVisible(true);
        this.setVisible(false);
         */
    }//GEN-LAST:event_btnCadProfessorActionPerformed

    private void btnCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadAlunoActionPerformed
        FrAluno dlgCadAluno = new FrAluno(this, true);

        // Configura o posicionamento relativo, faz o dialgo aparecer na mesma tela que o pai(qdo estamos mais de uma tela)
        dlgCadAluno.setLocationRelativeTo(this);
        dlgCadAluno.setVisible(true);

        /* Usando JFrame.
        Esta forma não é legal, dado que temos mais de uma aplicacao na barra de tarefas. 
        Dê preferencia por fazer a dinamica de telas usando JDialog como acima.
        
        FrAluno telaAluno = new FrAluno(this);
        telaAluno.setVisible(true);
        this.setVisible(false);
         */

    }//GEN-LAST:event_btnCadAlunoActionPerformed

    private void btnCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncionarioActionPerformed
        FrFuncionario dlgCadFuncionario = new FrFuncionario(this, true);

        // Configura o posicionamento relativo, faz o dialgo aparecer na mesma tela que o pai(qdo estamos mais de uma tela)
        dlgCadFuncionario.setLocationRelativeTo(this);
        dlgCadFuncionario.setVisible(true);

        /* Usando JFrame.
        Esta forma não é legal, dado que temos mais de uma aplicacao na barra de tarefas. 
        Dê preferencia por fazer a dinamica de telas usando JDialog como acima.
       
        FrFuncionario telaFuncionario = new FrFuncionario(this);
        telaFuncionario.setVisible(true);
        this.setVisible(false);
         */
    }//GEN-LAST:event_btnCadFuncionarioActionPerformed

    private void btnCadTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadTurmaActionPerformed
        FrTurma dlgCadTurma = new FrTurma(this, true);

        // Configura o posicionamento relativo, faz o dialgo aparecer na mesma tela que o pai(qdo estamos mais de uma tela)
        dlgCadTurma.setLocationRelativeTo(this);
        dlgCadTurma.setVisible(true);
    }//GEN-LAST:event_btnCadTurmaActionPerformed

    private void btnCadDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadDisciplinaActionPerformed
        FrDisciplina dlgCadDisciplina = new FrDisciplina(this, true);

        // Configura o posicionamento relativo, faz o dialgo aparecer na mesma tela que o pai(qdo estamos mais de uma tela)
        dlgCadDisciplina.setLocationRelativeTo(this);
        dlgCadDisciplina.setVisible(true);
    }//GEN-LAST:event_btnCadDisciplinaActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        int confirm = JOptionPane.showConfirmDialog(
                null,
                "Tem certeza que deseja sair?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_mnSairActionPerformed

    private void mnCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadAlunoActionPerformed
        btnCadAlunoActionPerformed(evt);
    }//GEN-LAST:event_mnCadAlunoActionPerformed

    private void mnCadProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadProfessorActionPerformed
       btnCadProfessorActionPerformed(evt);
    }//GEN-LAST:event_mnCadProfessorActionPerformed

    private void mnCadastrarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarFuncionariosActionPerformed
        btnCadFuncionarioActionPerformed(evt);
    }//GEN-LAST:event_mnCadastrarFuncionariosActionPerformed

    private void mnCadDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadDisciplinasActionPerformed
        btnCadDisciplinaActionPerformed(evt);
    }//GEN-LAST:event_mnCadDisciplinasActionPerformed

    private void mnCadTurmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadTurmasActionPerformed
        btnCadTurmaActionPerformed(evt);
    }//GEN-LAST:event_mnCadTurmasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadAluno;
    private javax.swing.JButton btnCadDisciplina;
    private javax.swing.JButton btnCadFuncionario;
    private javax.swing.JButton btnCadProfessor;
    private javax.swing.JButton btnCadTurma;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMenuPrincipal;
    private javax.swing.JMenuItem mnCadAluno;
    private javax.swing.JMenuItem mnCadDisciplinas;
    private javax.swing.JMenuItem mnCadProfessor;
    private javax.swing.JMenuItem mnCadTurmas;
    private javax.swing.JMenuItem mnCadastrarFuncionarios;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenuItem mnSair;
    // End of variables declaration//GEN-END:variables
}
