/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ifcoder.projetodacc_jpa.view;

import com.ifcoder.projetodacc_jpa.controller.TurmaController;
import com.ifcoder.projetodacc_jpa.controller.tableModel.TMAlunoTurma;
import com.ifcoder.projetodacc_jpa.model.entities.Aluno;
import com.ifcoder.projetodacc_jpa.model.entities.Turma;
import javax.swing.JOptionPane;
import com.ifcoder.projetodacc_jpa.model.exceptions.AlunoException;
import com.ifcoder.projetodacc_jpa.model.exceptions.ProfessorException;
import com.ifcoder.projetodacc_jpa.view.dialogs.DlgEscolhaAlunoParaTurma;
import com.ifcoder.projetodacc_jpa.view.dialogs.DlgEscolhaDisciplinaParaTurma;
import com.ifcoder.projetodacc_jpa.view.dialogs.DlgEscolhaProfessorParaTurma;
import javax.swing.JFrame;

/**
 *
 * @author joserui
 */
public class FrTurma extends javax.swing.JDialog {

    TurmaController turmaController;
    Long idTurmaEditando;
    Turma turmaCorrente = new Turma();

    public FrTurma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        turmaController = new TurmaController();
        idTurmaEditando = -1L;

        initComponents();

        this.habilitarCampos(false);
        this.limparCampos();

        turmaController.atualizarTabela(grdTurmas);
    }

    public void habilitarCampos(boolean flag) {
        for (int i = 0; i < panFormulario.getComponents().length; i++) {
            panFormulario.getComponent(i).setEnabled(flag);
        }
        btnAddAluno.setEnabled(flag);
        btnAddProfessor.setEnabled(flag);
        btnAddDisciplina.setEnabled(flag);

        edtDisciplina.setEnabled(false);
        edtProfessor.setEnabled(false);

    }

    public void limparCampos() {
        edtNome.setText("");
        edtHorario.setText("");
        edtAno.setText("");
        edtDisciplina.setText("");
        edtProfessor.setText("");
        turmaController.atualizarTabelaAlunoTurma(grdAlunos, turmaCorrente.getLstAlunos());
        
        tabsDados.setSelectedComponent(panGrdTurmas);
    }

    /**
     * O ideal seria entregar essa responsabiliadde para o controller para isso
     * deveriamos passar os componentes edt s
     *
     * OU senao criar um novo tipo representationModel, que será a representacao
     * do modelo na camada VIEW. Com isso criamos uma independencia da camada
     * MODEL.
     *
     * @param a
     */
    public void preencherFormulario(Turma turma) {
        edtNome.setText(turma.getNome());
        edtAno.setText(turma.getAno() + "");
        edtHorario.setText(turma.getHorario());
        edtProfessor.setText(turma.getProfessor().getNome());
        edtDisciplina.setText(turma.getDisciplina().getNome());

        turmaController.atualizarTabelaAlunoTurma(grdAlunos, turma.getLstAlunos());
        //tenho que puxar todo o objeto para turmaCorrente
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        panBotoes = new javax.swing.JPanel();
        btnNovo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        tabsDados = new javax.swing.JTabbedPane();
        panFormulario = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        edtNome = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        edtAno = new javax.swing.JTextField();
        lblHorario = new javax.swing.JLabel();
        edtHorario = new javax.swing.JTextField();
        panProfessores = new javax.swing.JPanel();
        edtProfessor = new javax.swing.JTextField();
        btnAddProfessor = new javax.swing.JButton();
        panDisciplina = new javax.swing.JPanel();
        edtDisciplina = new javax.swing.JTextField();
        btnAddDisciplina = new javax.swing.JButton();
        panAlunos = new javax.swing.JPanel();
        btnAddAluno = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        grdAlunos = new javax.swing.JTable();
        panGrdTurmas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        grdTurmas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de disciplinas");

        lblTitle.setFont(new java.awt.Font("Fira Sans", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Turmas");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        panBotoes.add(btnNovo);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panBotoes.add(btnEditar);

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panBotoes.add(btnCancelar);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        panBotoes.add(btnExcluir);

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        panBotoes.add(btnSalvar);

        lblNome.setText("Nome:");

        edtNome.setText("T01");

        lblAno.setText("Ano:");

        lblHorario.setText("Horário:");

        panProfessores.setBorder(javax.swing.BorderFactory.createTitledBorder("Professor"));
        panProfessores.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        edtProfessor.setPreferredSize(new java.awt.Dimension(280, 24));
        panProfessores.add(edtProfessor);

        btnAddProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plus_16x16.png"))); // NOI18N
        btnAddProfessor.setBorderPainted(false);
        btnAddProfessor.setContentAreaFilled(false);
        btnAddProfessor.setPreferredSize(new java.awt.Dimension(60, 22));
        btnAddProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProfessorActionPerformed(evt);
            }
        });
        panProfessores.add(btnAddProfessor);

        panDisciplina.setBorder(javax.swing.BorderFactory.createTitledBorder("Disciplina"));
        panDisciplina.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        edtDisciplina.setPreferredSize(new java.awt.Dimension(280, 24));
        panDisciplina.add(edtDisciplina);

        btnAddDisciplina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plus_16x16.png"))); // NOI18N
        btnAddDisciplina.setBorderPainted(false);
        btnAddDisciplina.setContentAreaFilled(false);
        btnAddDisciplina.setPreferredSize(new java.awt.Dimension(60, 22));
        btnAddDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDisciplinaActionPerformed(evt);
            }
        });
        panDisciplina.add(btnAddDisciplina);

        panAlunos.setBorder(javax.swing.BorderFactory.createTitledBorder("Alunos"));

        btnAddAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/plus_16x16.png"))); // NOI18N
        btnAddAluno.setText("Adicionar");
        btnAddAluno.setContentAreaFilled(false);
        btnAddAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAlunoActionPerformed(evt);
            }
        });

        grdAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        grdAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdAlunosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(grdAlunos);

        javax.swing.GroupLayout panAlunosLayout = new javax.swing.GroupLayout(panAlunos);
        panAlunos.setLayout(panAlunosLayout);
        panAlunosLayout.setHorizontalGroup(
            panAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAlunosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                    .addGroup(panAlunosLayout.createSequentialGroup()
                        .addComponent(btnAddAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panAlunosLayout.setVerticalGroup(
            panAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAlunosLayout.createSequentialGroup()
                .addComponent(btnAddAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panFormularioLayout = new javax.swing.GroupLayout(panFormulario);
        panFormulario.setLayout(panFormularioLayout);
        panFormularioLayout.setHorizontalGroup(
            panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panFormularioLayout.createSequentialGroup()
                            .addComponent(panDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24))
                        .addGroup(panFormularioLayout.createSequentialGroup()
                            .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panFormularioLayout.createSequentialGroup()
                                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 224, Short.MAX_VALUE))
                                .addComponent(edtNome))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAno, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(edtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(35, 35, 35)))
                    .addGroup(panFormularioLayout.createSequentialGroup()
                        .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panFormularioLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHorario)))
                            .addComponent(panProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(panAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panFormularioLayout.setVerticalGroup(
            panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFormularioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panFormularioLayout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panFormularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(panFormularioLayout.createSequentialGroup()
                        .addComponent(lblAno)
                        .addGap(48, 48, 48)))
                .addComponent(panDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHorario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(panFormularioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panAlunos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabsDados.addTab("Formulário", panFormulario);

        grdTurmas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        grdTurmas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdTurmasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(grdTurmas);

        javax.swing.GroupLayout panGrdTurmasLayout = new javax.swing.GroupLayout(panGrdTurmas);
        panGrdTurmas.setLayout(panGrdTurmasLayout);
        panGrdTurmasLayout.setHorizontalGroup(
            panGrdTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGrdTurmasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
                .addContainerGap())
        );
        panGrdTurmasLayout.setVerticalGroup(
            panGrdTurmasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGrdTurmasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
        );

        tabsDados.addTab("Todas as turmas", panGrdTurmas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabsDados)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabsDados, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        this.habilitarCampos(true);
        this.limparCampos();
        turmaCorrente = new Turma();
        tabsDados.setSelectedComponent(panFormulario);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {

            if (idTurmaEditando > 0) {
                turmaController.atualizarTurma(idTurmaEditando, edtNome.getText(), edtAno.getText(),
                        edtHorario.getText(),
                        turmaCorrente.getDisciplina(),
                        turmaCorrente.getProfessor(),
                        turmaCorrente.getLstAlunos());
            } else {
                turmaController.cadastrarTurma(edtNome.getText(), edtAno.getText(),
                        edtHorario.getText(),
                        turmaCorrente.getDisciplina(),
                        turmaCorrente.getProfessor(),
                        turmaCorrente.getLstAlunos());
            }
            //Comando bastante importante
            this.idTurmaEditando = -1L;

            turmaController.atualizarTabela(grdTurmas);
            this.habilitarCampos(false);
            this.limparCampos();
            
        } catch (AlunoException e) {
            System.err.println(e.getMessage());
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.idTurmaEditando = -1L;
        turmaCorrente = new Turma();
        
        this.limparCampos();
        this.habilitarCampos(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Turma turmaExcluida = (Turma) this.getObjetoSelecionadoNaGrid();

        if (turmaExcluida == null)
            JOptionPane.showMessageDialog(this, "Primeiro selecione um registro na tabela.");
        else {

            int response = JOptionPane.showConfirmDialog(null,
                    "Deseja exlcuir o Aluno  \n("
                    + turmaExcluida.getNome() + ", "
                    + turmaExcluida.getDisciplina().getNome() + ") ?",
                    "Confirmar exclusão",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.OK_OPTION) {

                try {
                    this.idTurmaEditando = turmaCorrente.getId();
                    turmaController.excluirTurma(idTurmaEditando);
                    turmaController.atualizarTabela(grdTurmas);
                    JOptionPane.showMessageDialog(this, "Exclusão feita com sucesso!");
                    this.idTurmaEditando = -1L;
                } catch (ProfessorException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        turmaCorrente = (Turma) this.getObjetoSelecionadoNaGrid();

        if (turmaCorrente == null)
            JOptionPane.showMessageDialog(this, "Primeiro selecione um registro na tabela.");
        else {
            this.limparCampos();
            this.habilitarCampos(true);
            this.preencherFormulario(turmaCorrente);
            this.idTurmaEditando = Long.valueOf(turmaCorrente.getId() + "");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * Retorna o objeto (classe) da linha selecionada na grid.
     *
     * Uso a estratégia do metodo getValueAt() la na TableModel, receber coluna
     * -1 e retornar o objeto ao inves de uma célula.
     *
     * @return
     */
    private Object getObjetoSelecionadoNaGrid() {
        int rowCliked = grdTurmas.getSelectedRow();
        Object obj = null;
        if (rowCliked >= 0) {
            obj = grdTurmas.getModel().getValueAt(rowCliked, -1);
        }
        return obj;
    }

    private void btnAddProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProfessorActionPerformed
        DlgEscolhaProfessorParaTurma tela = new DlgEscolhaProfessorParaTurma(new JFrame(), true, turmaCorrente);
        tela.setVisible(true);

        edtProfessor.setText(turmaCorrente.getProfessor().getNome());
    }//GEN-LAST:event_btnAddProfessorActionPerformed

    private void btnAddAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAlunoActionPerformed
        DlgEscolhaAlunoParaTurma tela = new DlgEscolhaAlunoParaTurma(new JFrame(), true, turmaCorrente);
        tela.setVisible(true);

        turmaController.atualizarTabelaAlunoTurma(grdAlunos, turmaCorrente.getLstAlunos());

    }//GEN-LAST:event_btnAddAlunoActionPerformed

    private void grdAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdAlunosMouseClicked
        //pego a coluna que foi o clique
        int column = grdAlunos.columnAtPoint(evt.getPoint());

        //se tiver sido em cima da imagem REMOVER
        if (column == 2) {
            //pegamos o objeto Aluno como um todo
            int rowCliked = grdAlunos.getSelectedRow();
            Object obj = null;
            if (rowCliked >= 0) {
                obj = grdAlunos.getModel().getValueAt(rowCliked, -1);
            }

            Aluno aluno = (Aluno) obj;
            int response = JOptionPane.showConfirmDialog(null,
                    "Deseja exlcuir o Aluno  \n("
                    + aluno.getNome() + ") ?",
                    "Confirmar exclusão",
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.OK_OPTION) {
                TMAlunoTurma tableModel = (TMAlunoTurma) grdAlunos.getModel();
                tableModel.getLista().remove(obj);
                turmaController.atualizarTabelaAlunoTurma(grdAlunos, tableModel.getLista());
            }
        }
    }//GEN-LAST:event_grdAlunosMouseClicked

    private void grdTurmasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdTurmasMouseClicked
        if (evt.getClickCount() == 2) {
            btnEditarActionPerformed(null);
            tabsDados.setSelectedComponent(panFormulario);
        }
    }//GEN-LAST:event_grdTurmasMouseClicked

    private void btnAddDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDisciplinaActionPerformed
        DlgEscolhaDisciplinaParaTurma tela = new DlgEscolhaDisciplinaParaTurma(new JFrame(), true, turmaCorrente);
        tela.setVisible(true);

        edtDisciplina.setText(turmaCorrente.getDisciplina().getNome());
    }//GEN-LAST:event_btnAddDisciplinaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAluno;
    private javax.swing.JButton btnAddDisciplina;
    private javax.swing.JButton btnAddProfessor;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField edtAno;
    private javax.swing.JTextField edtDisciplina;
    private javax.swing.JTextField edtHorario;
    private javax.swing.JTextField edtNome;
    private javax.swing.JTextField edtProfessor;
    private javax.swing.JTable grdAlunos;
    private javax.swing.JTable grdTurmas;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panAlunos;
    private javax.swing.JPanel panBotoes;
    private javax.swing.JPanel panDisciplina;
    private javax.swing.JPanel panFormulario;
    private javax.swing.JPanel panGrdTurmas;
    private javax.swing.JPanel panProfessores;
    private javax.swing.JTabbedPane tabsDados;
    // End of variables declaration//GEN-END:variables

}
